language: node_js
node_js:
  - lts/*
  - node
sudo: required
addons:
  chrome: stable
before_install:
  - 'git config --global url."git@github.com:".insteadOf "https://github.com/"'
install:
  - npm i -g lsc codecov
  - npm install
script:
  - npm audit --audit-level high
  - npm run build
  - npm run lint
  - xvfb-run npm run coverage
  - codecov
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: release
      if: branch = master
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run semantic-release
